### ISSUE TITLE
Can't create superuser and get access to admin side

### ISSUE THREAD

**Issue by aorzh** [discolabs/django-shopify-auth#35]
When I'm trying run  python manage.py createsuperuser
I'm getting: 
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/Users/alex/virtualenvs/shopdemo/lib/python3.5/site-packages/django/core/management/__init__.py", line 350, in execute_from_command_line
    utility.execute()
  File "/Users/alex/virtualenvs/shopdemo/lib/python3.5/site-packages/django/core/management/__init__.py", line 342, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/Users/alex/virtualenvs/shopdemo/lib/python3.5/site-packages/django/core/management/base.py", line 348, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/Users/alex/virtualenvs/shopdemo/lib/python3.5/site-packages/django/contrib/auth/management/commands/createsuperuser.py", line 52, in execute
    return super(Command, self).execute(*args, **options)
  File "/Users/alex/virtualenvs/shopdemo/lib/python3.5/site-packages/django/core/management/base.py", line 399, in execute
    output = self.handle(*args, **options)
  File "/Users/alex/virtualenvs/shopdemo/lib/python3.5/site-packages/django/contrib/auth/management/commands/createsuperuser.py", line 173, in handle
    self.UserModel._default_manager.db_manager(database).create_superuser(**user_data)
TypeError: create_superuser() missing 1 required positional argument: 'domain'

Is there any chance to get access to admin side?

**Comment by gavinballard** [comment]
@aorzh I imagine this is probably a similar issue to https://github.com/discolabs/django-shopify-auth/issues/34. What version of Django are you using? It may not be supported.

**Comment by aorzh** [comment]
@gavinballard , no its more about creating costom user model I think.. Im use 1.9 as was described in readme.

**Comment by gavinballard** [comment]
@aorzh Ah, sorry, I meant this issue: #22. A fix for this was provided in #23, but it hasn't been merged due to a lack of tests.

**Comment by gavinballard** [comment]
This should now be resolved thanks to #37.
