### ISSUE TITLE
shopify_auth_urls module not found when including urls for Django 2.0

### ISSUE THREAD

**Issue by owenfi** [discolabs/django-shopify-auth#43]
It's probably something with my configuration, so I'm attempting to start a fresh app to see if it runs cleanly, but for some reason I am currently getting this error:

`ModuleNotFoundError: No module named 'shopify_auth_urls'`

I initially though it might be a typo in the import string (since the old version uses `shopfiy_auth.urls` but that doesn't appear to be the case either.

Full trace:

    Unhandled exception in thread started by <_pydev_bundle.pydev_monkey._NewThreadStartupWithTrace object at 0x1072c4e10>
    Traceback (most recent call last):
      File "/Applications/PyCharm.app/Contents/helpers/pydev/_pydev_bundle/pydev_monkey.py", line 589, in __call__
        return self.original_func(*self.args, **self.kwargs)
      File "/Users/owen/.virtualenvs/sotd/lib/python3.6/site-packages/django/utils/autoreload.py", line 225, in wrapper
        fn(*args, **kwargs)
      File "/Users/owen/.virtualenvs/sotd/lib/python3.6/site-packages/django/core/management/commands/runserver.py", line 120, in inner_run
        self.check(display_num_errors=True)
      File "/Users/owen/.virtualenvs/sotd/lib/python3.6/site-packages/django/core/management/base.py", line 364, in check
        include_deployment_checks=include_deployment_checks,
      File "/Users/owen/.virtualenvs/sotd/lib/python3.6/site-packages/django/core/management/base.py", line 351, in _run_checks
        return checks.run_checks(**kwargs)
      File "/Users/owen/.virtualenvs/sotd/lib/python3.6/site-packages/django/core/checks/registry.py", line 73, in run_checks
        new_errors = check(app_configs=app_configs)
      File "/Users/owen/.virtualenvs/sotd/lib/python3.6/site-packages/django/core/checks/urls.py", line 40, in check_url_namespaces_unique
        all_namespaces = _load_all_namespaces(resolver)
      File "/Users/owen/.virtualenvs/sotd/lib/python3.6/site-packages/django/core/checks/urls.py", line 57, in _load_all_namespaces
        url_patterns = getattr(resolver, 'url_patterns', [])
      File "/Users/owen/.virtualenvs/sotd/lib/python3.6/site-packages/django/utils/functional.py", line 36, in __get__
        res = instance.__dict__[self.name] = self.func(instance)
      File "/Users/owen/.virtualenvs/sotd/lib/python3.6/site-packages/django/urls/resolvers.py", line 536, in url_patterns
        patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
      File "/Users/owen/.virtualenvs/sotd/lib/python3.6/site-packages/django/utils/functional.py", line 36, in __get__
        res = instance.__dict__[self.name] = self.func(instance)
      File "/Users/owen/.virtualenvs/sotd/lib/python3.6/site-packages/django/urls/resolvers.py", line 529, in urlconf_module
        return import_module(self.urlconf_name)
      File "/Users/owen/.virtualenvs/sotd/lib/python3.6/importlib/__init__.py", line 126, in import_module
        return _bootstrap._gcd_import(name[level:], package, level)
      File "<frozen importlib._bootstrap>", line 994, in _gcd_import
      File "<frozen importlib._bootstrap>", line 971, in _find_and_load
      File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
      File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
      File "<frozen importlib._bootstrap_external>", line 678, in exec_module
      File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
      File "/Users/owen/Documents/code/sotd/sotd/urls.py", line 28, in <module>
        path('login/', include('shopify_auth_urls')),
      File "/Users/owen/.virtualenvs/sotd/lib/python3.6/site-packages/django/urls/conf.py", line 34, in include
        urlconf_module = import_module(urlconf_module)
      File "/Users/owen/.virtualenvs/sotd/lib/python3.6/importlib/__init__.py", line 126, in import_module
        return _bootstrap._gcd_import(name[level:], package, level)
      File "<frozen importlib._bootstrap>", line 994, in _gcd_import
      File "<frozen importlib._bootstrap>", line 971, in _find_and_load
      File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked
    ModuleNotFoundError: No module named 'shopify_auth_urls'

**Comment by owenfi** [comment]
Same reproduces on a fresh project.

It turns out to be a typo in the Readme & because the version I am running doesn't have this change:
https://github.com/discolabs/django-shopify-auth/commit/11f77bfa4e74d0dede7a21aec3d0908211985d8b#diff-4d651c6555a06f76de63f614b2a9f5fb

Applying the correct import manually works fine

    [owen: demo_auth]$ pip freeze
    Django==2.0.4
    django-shopify-auth==0.7.0
    pyactiveresource==2.1.2
    pytz==2018.4
    PyYAML==3.12
    ShopifyAPI==3.0.0
    six==1.11.0

**Comment by owenfi** [comment]
I didn't get too much further on this - it seemed to be working fine, but as soon as I went to register my account / setup oauth I came across the "private apps don't use OAuth" and realized I could just use https://github.com/Shopify/shopify_python_api directly. It seems like this isn't required for my personal use case so I pulled it out. Feel free to close this ticket, or bring in my PR: https://github.com/discolabs/django-shopify-auth/pull/44

**Comment by stlk** [comment]
Resolved in #44
